### PR TITLE
Add support for Qt 6

### PR DESCRIPTION
**Pull request by visuve**
@hasherezade this did not turn out to be that bad after all!

NOTE: might have minor build errors on Qt 4, please test!

### CODE REVIEW

**Comment by hasherezade** [comment]
Looks great, thank you! :)
There are just few minor things to fix, could you apply this patch?

```diff
diff --git a/pe-bear/CMakeLists.txt b/pe-bear/CMakeLists.txt
index 60f5ce0..31ff734 100644
--- a/pe-bear/CMakeLists.txt
+++ b/pe-bear/CMakeLists.txt
@@ -248,7 +248,7 @@ set (pebear_srcs
 )
 
 set (pebear_hdrs
-	PEbear.h
+	PEBear.h
 	REbear.h
 	${pebear_threads_hdrs}
 	${pebear_base_hdrs}
diff --git a/pe-bear/PEBear.h b/pe-bear/PEBear.h
index 157fcb0..2367169 100644
--- a/pe-bear/PEBear.h
+++ b/pe-bear/PEBear.h
@@ -1,5 +1,5 @@
 #pragma once
-
+#include <QtGlobal>
 #if QT_VERSION >= QT_VERSION_CHECK(5, 0, 0)
 	#include <QtWidgets>
 #else
@@ -7,3 +7,4 @@
 	typedef QRegularExpression QRegExp;
 	typedef QRegularExpressionValidator QRegExpValidator;
 #endif
+
```

**Comment by hasherezade** [comment]
Anyways, I can merge it as is, and then apply the patch.

**Comment by hasherezade** [comment]
@visuve - after few  more fixes, it builds fine with Qt4!
https://github.com/hasherezade/pe-bear/commit/29c18c43a7fe56cb6f1fadfed9ef9b5abe78e1c3

[PE-bear_0.6.7.4_qt4_x86_win_vs10.zip](https://github.com/hasherezade/pe-bear/files/14891862/PE-bear_0.6.7.4_qt4_x86_win_vs10.zip)

**Comment by visuve** [comment]
@hasherezade amazing, now it works on all three!

**Pull request merged**
