### PR TITLE
Langeuage Update

### PR DESCRIPTION
**Pull request by fairycn**
Updated language files based on existing code

### CODE REVIEW

**Comment by hasherezade** [comment]
Thank you @fairycn !
But there are some lines here and there that looks like an error. As if some automated text replacing went wrong. Look at this:

err1

I mean, instead of "File reloaded..." there is "File reloade../pe-bear" and so on...
It occurs in multiple lines, I just showed one example.
Can you please fix this?

**Comment by fairycn** [comment]
Fixed this issue, not sure why [d:] was matching the path info I replaced (guessing ed escaped to disc letter caused it to match)

**Comment by hasherezade** [comment]
thank you @fairycn - but I see that not all are fixed, for example:

https://github.com/fairycn/pe-bear/blob/e84375ea9f323869594ec2f2cd12a0efea75c76a/Language/PE-bear.ts#L171

please fix all of them, and I will merge

**Comment by hasherezade** [comment]
@fairycn - thank you, looks better! does the `.qm` file with Chinese language does not require rebuilding to follow the changes?

**Comment by fairycn** [comment]
Yes, the question of whether or not the ts file generated by the translation (with the replacement path conforming to the previous convention) doesn't affect the use of qm

**Comment by hasherezade** [comment]
ok, thank you!

**Pull request merged**
